version: '3.9'

services:
  # =app
  app:
    image: "sindriainc/nginx-php:${NGINX_PHP_TAG}-${NGINX_PHP_VERSION}-${NGINX_PHP_TAG_ENV}"
    container_name: "${APP_NAME}"
    command: "tail -f /dev/null"
    #command: /bin/bash -c "rmdir /var/www/app; ln -s /home/sindria/Projects/Sindria/sindria-devops-lab/tools/zbx-manager/src /var/www/app; tail -f /dev/null"
    volumes:
      - "${CODE_PATH}:${APP_CODE_PATH}"
      #- "xdev-sindria_projects:/home/sindria/Projects"
    hostname: "${APP_NAME}.local"
    #ports:
    #  - "8080:80"
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #networks:
    #  vpc_<app-name>:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"


# =networks
networks:
  default:
    name: "vpc_${APP_NAME}"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_<app-name>:
#    external: true

# =volumes
#volumes:
#  xdev-sindria_projects:
#    external: true
